In [10]:
from sparql_dataframe import get
endpoint = 'https://dati.cultura.gov.it/sparql'

query = '''
SELECT DISTINCT(?s) (year(xsd:dateTime(?starttime)) as ?startTime) (year(xsd:dateTime(?endtime)) as ?endTime) WHERE {
 ?s a cis:CulturalEvent;
rdfs:label ?event.
?s tiapit:atTime ?time.
?time tiapit:startTime ?starttime; 
tiapit:endTime ?endtime.
}
'''

EventsYears = get(endpoint, query)
EventsYears

                                                       s  startTime  endTime
0      http://dati.beniculturali.it/mibact/eventi/res...       2022     2022
1      http://dati.beniculturali.it/mibact/eventi/res...       2022     2022
2      http://dati.beniculturali.it/mibact/eventi/res...       2022     2022
3      http://dati.beniculturali.it/mibact/eventi/res...       2022     2022
4      http://dati.beniculturali.it/mibact/eventi/res...       2022     2022
...                                                  ...        ...      ...
21179  http://dati.beniculturali.it/mibact/eventi/res...       2023     2023
21180  http://dati.beniculturali.it/mibact/eventi/res...       2023     2023
21181  http://dati.beniculturali.it/mibact/eventi/res...       2023     2023
21182  http://dati.beniculturali.it/mibact/eventi/res...       2023     2023
21183  http://dati.beniculturali.it/mibact/eventi/res...       2023     2023

[21184 rows x 3 columns]

In [13]:
EventCountPerYear = {}

for idx, row in EventsYears.iterrows():
    if row["startTime"] == row["endTime"]:
        if row["startTime"] not in EventCountPerYear:
            EventCountPerYear[row["startTime"]] = 1
        else:
            EventCountPerYear[row["startTime"]] += 1
    elif row["startTime"] < row["endTime"]:
        if row["startTime"] not in EventCountPerYear:
            EventCountPerYear[row["startTime"]] = 1
        else:
            EventCountPerYear[row["startTime"]] += 1
        if row["endTime"] not in EventCountPerYear:
            EventCountPerYear[row["endTime"]] = 1
        else:
            EventCountPerYear[row["endTime"]] += 1
        OtherYears = int(row["endTime"]) - int(row["startTime"])
        for i in range(OtherYears):
            year = int(row["startTime"]) + 1
            if year not in EventCountPerYear:
                EventCountPerYear[year] = 1
            else:
                EventCountPerYear[year] += 1
    else:         
        if row["startTime"] not in EventCountPerYear:
            EventCountPerYear[row["startTime"]] = 1
        else:
            EventCountPerYear[row["startTime"]] += 1
        if row["endTime"] not in EventCountPerYear:
            EventCountPerYear[row["endTime"]] = 1
        else:
            EventCountPerYear[row["endTime"]] += 1
EventCountPerYear

{2022: 6449,
 2021: 5355,
 2023: 755,
 2020: 7283,
 2018: 15,
 2013: 1,
 2014: 11,
 2019: 2824,
 2015: 5,
 2016: 2,
 2017: 3,
 2010: 1}